version: "3.2"

services:
  ares_substrate_tools:
    build:
      context: .
#      context: https://xxxx
      dockerfile: ./Dockerfile
    container_name: ares_substrate_tools
    image: aresprotocollab/ares_substrate_tools
    ports:
      - "6680:80"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"